//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCarros
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductComments = new HashSet<ProductComment>();
        }
    
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal ListPrice { get; set; }
        public string Description { get; set; }
        public Nullable<int> MarkId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Picture { get; set; }
        public string Engine { get; set; }
        public string ColorInside { get; set; }
        public string ColorOutside { get; set; }
        public string Fuel { get; set; }
        public string Transmission { get; set; }
        public string Traction { get; set; }
        public Nullable<int> Door { get; set; }
        public Nullable<int> Passenger { get; set; }
        public Nullable<int> Year { get; set; }
        public string Status { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> Mileage { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Mark Mark { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductComment> ProductComments { get; set; }
    }
}
